### ISSUE TITLE
Demo weirdly broken with adblocker

### ISSUE THREAD

**Issue by dimaqq** [ModusCreateOrg/react-idle#10]
Chrome stable 71.0.3578.98, uBlock origin 1.17.4, MacOS.

* load the demo page https://react-idle.modus.app/
* "render on idle" should be off
* click some months (>5)
* quickly tab some months (>5)
* quickly tick "render on idle"

After the last step, the screen starts blinking and months are continuously selected and deselected.

It's as if the page "buffered" really many tabs and is now replaying each change.

The weirdness doesn't stop on its own.

Leaving the browser tab (e.g. focusing on another tab or window), allows process to conclude.

**Comment by grgur** [comment]
Thanks for reporting this. I wonder if #9 will help once it's merged. rAF and global queue might be helpful here

**Comment by grgur** [comment]
v1.1.0 published to npm. Please reopen the issue if the problem persists. Thanks, @dimaqq
