### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mschwartz** [ModusCreateOrg/react-idle#3]
The component looks like it should work.  We need to add examples.

**Comment by grgur** [comment]
I have one requirement - that we don't add any dependencies to package.json. I like the idea behind this: https://github.com/bvaughn/react-virtualized/tree/master/playground

**Comment by mschwartz** [comment]
Maybe we should close this issue.  I think unit tests will be sufficient.

Example code can be in the readme or wiki, IMO.

**Comment by grgur** [comment]
We definitely need an example. I'll take that on

**Comment by mschwartz** [comment]
Sounds like a plan.

The thing is, you don't want to add any dependencies (but maybe you can have a package.json in the examples (in each if you have multiple).

Plus, I don't know how someone is going to notice the example is actually working :)
