### ISSUE TITLE
Views on dom manipulation in requestIdleCallback

### ISSUE THREAD

**Issue by swapnil95** [ModusCreateOrg/react-idle#7]
It suggested that we should avoid dom updates in the `requestIdleCallback` and use `requestAnimationFrame` instead. Will using this library cause dom updates during `requestIdleCallback` or is it upto react to find the right time and handle it accordingly?

**Comment by grgur** [comment]
@swapnil95 great question. `requestIdleCallback` will trigger a vdom update only and React handles the right time to update the DOM. Regardless of that, I think you have a point - we should wrap the callback into a `rAF` just to play safe

**Comment by grgur** [comment]
This was fixed in v1.1.0. Thank you for reporting @swapnil95
